version: "3.9"
services:
  app:
    build: ./config/php
    volumes:
      - ./src:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  # 追記
  db:
    build: ./config/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:


