version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host